README.md
specs/spark-application.yaml
specs/spark-operator-service.yaml
specs/spark-service-monitor.yaml

___The changes came from https://github.com/mesosphere/data-services-tooling/pull/42___
___The description is copy-pasted from there___
The reason, why Spark's telemetry metrics were not appeared in Prometheus, is incompatibility between Google's spark-operator and prometheus-operator (coreos), which is shipped preinstalled within Konvoy. (Spark operator expects to have deals with kube-prometheus). More specifically, the prometheus-operator uses crafted services discovery approach, which is employ its own CRD - ServiceMonitor kind. So, the general rules to make metrics available for scrape by Prometheus (Prometheus-operator) are following:
ServiceMonitor should be created, having specified appropriate service endpoint selector AND matching namespace if interested pods are in non-default …

DCOS-59088 [DS] [Spark Operator] Make Spark operator metrics available in Prometheus/Grafana

---

.github/PULL_REQUEST_TEMPLATE

This PR adds the template for standardization of PRs. It was adopted from [mesosphere/spark-build](https://github.com/mesosphere/spark-build/blob/master/.github/PULL_REQUEST_TEMPLATE)
Most of the time we request clarifications from contributors related but not limited to the ones outlined in the template. The template will save reviewers a few cycles by providing those questions and structure upfront.

Added Github PR template

---

.gitignore
README.md
kudo-operator/operator.yaml
kudo-operator/params.yaml
kudo-operator/templates/spark-operator-deployment.yaml
kudo-operator/templates/spark-operator-rbac.yaml
kudo-operator/templates/spark-operator-serviceaccount.yaml
kudo-operator/templates/spark-rbac.yaml
kudo-operator/templates/spark-serviceaccount.yaml
kudo-operator/templates/webhook-cleanup-job.yaml
kudo-operator/templates/webhook-init-job.yaml
kudo-operator/templates/webhook-service.yaml
scripts/install_operator.sh
scripts/remove_operator.py
specs/spark-application.yaml
specs/spark-namespace.yaml

Resolves [DCOS-59164: Port Spark Operator Helm Chart to KUDO](https://jira.mesosphere.com/browse/DCOS-59164).
* added KUDO configuration and templates for Spark Operator based on [Spark Operator Helm Chart](https://github.com/helm/charts/tree/master/incubator/sparkoperator).
* updated installation script
* added `spark` namespace spec
* added cleanup script to teardown installed KUDO operator
* Operator uses the latest Docker image built from this repo using `make docker-build`
* this image doesn't support `apiVersion: v1beta2` so the upgrade will be addressed in a separate PR
Notes:
* `kudo-operator` directory is temporary and will be moved to [kudobuilder/operators](https://github.com/kudobuilder/operators) once stabilized
* make sure you're using KUDO CLI 0.6.0
```
$> kubectl kudo …
```

[DCOS-59164] Ported Spark Operator Helm Chart to KUDO (PoC)

---

Makefile
README.md
VERSION
scripts/install_operator.sh
specs/spark-namespace.yaml

**What is addressed in this PR?**
* synced mesosphere/spark-on-k8s-operator with the upstream
* updated spark-on-k8s-operator submodule in mesosphere/kudo-spark-operator to point to v1beta2-1.0.0-2.4.4 tag
* updated tooling to be able to build a working operator image which supports v1beta2 API version
Images build logs - [make_operator-build.log](https://github.com/mesosphere/kudo-spark-operator/files/3678844/make_operator-build.log)
kudo-spark-operator installation logs - [install_operator.log](https://github.com/mesosphere/kudo-spark-operator/files/3681171/install_operator.log)
The operator/controller logs - [logs-from-sparkoperator-in-spark-operator-sparkoperator-6bc599f75c-5xjff.txt](https://github.com/mesosphere/kudo-spark-operator/files/3681186/logs-from-sparkoperator-in-spark-opera …

DCOS-59489 [DS] [Spark Operator] Update KUDO Spark Operator to support latest apiVersion

---

Makefile
images/spark/Dockerfile
images/spark/conf/metrics.properties
images/spark/conf/prometheus.yaml
specs/spark-namespace.yaml

This PR updates the steps required to setup Prometheus JMX exporter to adhere to the upstream
Using scripts from this repo.
```
make spark-build DOCKER_REPO_NAME=<personal_docker_hub>
make docker-push
make cluster-create
make install
kubens spark  
kubectl create -f specs/spark-operator-service.yaml
kubectl create -f specs/spark-service-monitor.yaml
kubectl create -f specs/spark-application.yaml 
```
Then go to Prometeus from Konvoy cluster dashboard and verify the metrics:

Update setup for the Prometheus JMX exporter

---

.gitignore
Makefile

This PR adds default configuration parameters for Konvoy cluster size and instance types and provides support for changes implemented in https://github.com/mesosphere/data-services-kudo/pull/34
To support cluster size modifications needed for integration testing (e.g. default cluster size is . not sufficient for testing shuffle jobs)
By running `make install WORKER_NODE_INSTANCE_TYPE=m4.xlarge WORKER_NODE_COUNT=6` and verifying that cluster.yaml was updated and created cluster has specified type and number of worker nodes.

Added number of nodes and instance type configuration support for Konvoy

---

kudo-operator/operator.yaml
kudo-operator/params.yaml
scripts/install_operator.sh
specs/spark-applications-crds.yaml

This PR is a workaround for KUDO issue preventing the installation of CRDs as a part of KUDO operator.
This PR temporary removes CRDs from KUDO Operator resources and makes CRD installation external to the Operator.
KUDO Spark installation was failing with the following error in KUDO controller logs:
```
2019/10/10 17:57:38 PlanExecution: Error when applying StrategicMergePatch to object /scheduledsparkapplications.sparkoperator.k8s.io: merging an object in json but data type is not struct, instead is: map
```
Full log attached: [kudo-spark-crds-merge-failure.log](https://github.com/mesosphere/kudo-spark-operator/files/3714921/kudo-spark-crds-merge-failure.log)
By running `make install` on a newly created cluster, checking controller logs, and submitting Spark Application with `kubectl …

Extract Operator CRDs installation from KUDO

---

images/build.sh
images/spark/Dockerfile

Resolves [DCOS-59596 [DS] [Spark Operator] Enable Docker image publishing in CI builds](https://jira.mesosphere.com/browse/DCOS-59596)
Changes:
- fix `build.sh` to respect KUDO CI contract
- verification of CI changes implemented by @alembiewski 
These changes were needed to verify that Docker images are built by CI when changed and fix the issue in `build.sh`.
- By adding artificial change (reverted later) and verifying that Docker publishing step is working. TC build: [link](https://teamcity.mesosphere.io/viewLog.html?buildId=2349878&buildTypeId=Frameworks_DataServices_Kudo_Spark_Pr_SparkPrKonvoyKudoV073&tab=buildResultsDiv), build logs: [PR_Spark_PR_Konvoy_KUDO-v0.7.3_30.log.zip](https://github.com/mesosphere/kudo-spark-operator/files/3719720/PR_Spark_PR_Konvoy_KUDO-v0.7.3_30.log.zip)

[DCOS-59596] Enable Docker image publishing in CI builds

---

MONITORING.md
README.md
images/operator/Dockerfile
images/spark/Dockerfile
kudo-operator/operator.yaml
specs/spark-application.yaml
tests/utils/common.go

Resolves [DCOS-60155: Use mesosphere/spark distribution in Docker images](https://jira.mesosphere.com/browse/DCOS-60155).
This PR migrates Spark base and operator images to mesosphere/spark distribution built with Hadoop 2.9.2 and `hadoop-cloud` support.
The process of building Spark K8s distribution is described in [corporate wiki](https://wiki.mesosphere.com/display/ENG/Building+Spark+Operator+distribution+and+images).
Apache Spark distribution tarball which is built with Hadoop 2.7 lacks `hadoop-cloud` profile dependencies and prevents us from using S3A locations for SHS and using newer credentials providers implementations for application which use session tokens for S3 access.
- integration tests from this repo
- scale tests from …

Migrated images to Mesosphere Spark distribution

---

Makefile
images/builder/Dockerfile
tests/basic_test.go
tests/run.sh
tests/utils/common.go
tests/utils/job_submit.go
tests/utils/k8s.go
tests/utils/spark_operator.go

Resolves [DCOS-60183](https://jira.mesosphere.com/browse/DCOS-60183)
Applies `go-test-teamcity` to the `go test ...` output
Until Teamcity is updated to a version that supports `go test` out of the box (if ever), we need a workaround to achieve the following:
- Recognize and list individual tests in a build
- Build status should reflect test run results
Both locally and in Teamcity

DCOS-60183: Teamcity test output fix

---

kudo-operator/params.yaml
kudo-operator/templates/spark-application-metrics-service.yaml
kudo-operator/templates/spark-history-server-deployment.yaml
kudo-operator/templates/spark-history-server-service.yaml
kudo-operator/templates/spark-operator-crds.yaml
kudo-operator/templates/spark-operator-deployment.yaml
kudo-operator/templates/spark-operator-metrics-service.yaml
kudo-operator/templates/spark-operator-rbac.yaml
kudo-operator/templates/spark-operator-serviceaccount.yaml
kudo-operator/templates/spark-rbac.yaml
kudo-operator/templates/spark-serviceaccount.yaml
kudo-operator/templates/webhook-cleanup-job.yaml
kudo-operator/templates/webhook-init-job.yaml
kudo-operator/templates/webhook-service.yaml

Resolves [DCOS-60223: Boolean check fix](https://jira.mesosphere.com/browse/DCOS-60223)
It introduces the fix for Boolean parameter being treated as String by KUDO Templating. Modifies all the IF conditions involved Boolean values to have equality check with the String "true".
In KUDO template, Boolean values are treated as String, so all the IF conditions were checking it correctly.
By manually running `make install`.

[DCOS-60223] [DS] [Spark Operator] Boolean parameters are not being treated as Boolean by KUDO

---

kudo-operator/docs/latest/limitations.md
kudo-operator/docs/latest/release-notes.md
kudo-operator/docs/latest/versions.md

Resolves [DCOS-59715: Add release notes, limitations, and versions sections to KUDO Spark docs](https://jira.mesosphere.com/browse/DCOS-59715).
This PR adds documentation for component versions, limitations, and release notes.
The change is needed as a part of the operator documentation.
* tests from this repo
* by reviewing rendered markdown and verifying that links and the markup are correctly displayed

[DCOS-59715] Added docs for versions, limitations, and release notes

---

tests/basic_test.go
tests/utils/k8s.go

Resolves integration test issues when a namespace is not immediately deleted after an API call, resulting in errors like this in further tests:
```
Error from server (Forbidden): error when creating "/tmp/job-886088610": sparkapplications.sparkoperator.k8s.io "linear-regression" is forbidden: unable to create new content in namespace kudo-spark-operator-testing because it is being terminated 
```
With `make cluster-create` and `make test`

Verify that a namespace is truly deleted after an API call

---

.github/CODEOWNERS

Introduce CODEOWNERS file with the list of entire team members' names.
The folks mentioned in the file will be marked as code owners in GitHub UI. And what more important:
>Code owners are automatically requested for review when someone opens a pull request that modifies code that they own. Code owners are not automatically requested to review draft pull requests. For more information about draft pull requests, see "About pull requests."

Added CODEOWNERS file with list of names

---

kudo-operator/docs/latest/configuration.md

Resolves [DCOS-59712: Document configuration of KUDO Spark Operator](https://jira.mesosphere.com/browse/DCOS-59712).
This PR adds documentation for the main configuration properties supported and verified for the beta release.
The change is needed as a part of the operator documentation.
* tests from this repo
* by reviewing rendered markdown and verifying that links and the markup are correctly displayed

[DCOS-59712] Added configuration docs for KUDO Spark

---

kudo-operator/docs/latest/installation.md

Resolves [DCOS-59711: Document installation of KUDO Spark Operator](https://jira.mesosphere.com/browse/DCOS-59711)
This PR adds documentation for the basic installation steps for the beta release.
The change is needed as a part of the operator documentation.
* tests from this repo
* by reviewing rendered markdown and verifying that links and the markup are correctly displayed

[DCOS-59711] Added installation documentation for KUDO Spark

---

README.md
images/builder/Dockerfile

Resolves [DCOS-60483: Update KUDO version](https://jira.mesosphere.com/browse/DCOS-60483)
Updates KUDO version to `0.7.5` mentioned in the project.
There were some places where still KUDO version was `0.7.3`, which we are no longer supporting.
Ran `make install` and `make tests` locally

[DCOS-60483] [DS] [Spark Operator] Update the KUDO version from 0.7.3 to 0.7.5

---

images/operator/Dockerfile

This PR updates the Operator Dockerfile to explicitly use source code from git submodule and removes redundant `COPY`:
```
WORKDIR ${GOPATH}/src/github.com/GoogleCloudPlatform/spark-on-k8s-operator
COPY Gopkg.toml Gopkg.lock ./
``` 
To simplify the troubleshooting of the image build process and remove redundant code.
- integration tests from this repo

Updated Operator image build paths to explicitly use source code from git module

---

tests/tenancy_test.go

This PR removes a check for metrics service from multi-tenancy tests as it is not installed as a part of KUDO Spark.
After the changes introduced in https://github.com/mesosphere/kudo-spark-operator/pull/48 we removed metrics service installation from KUDO, however, were still verifying it is installed in the tests.
* integration tests from this repo

Removing metrics service from components check in multitenancy tests

---

.gitignore
scale-tests/README.md
scale-tests/scripts/install.sh
scale-tests/scripts/scale_test.sh
scale-tests/scripts/terasort.sh
scale-tests/scripts/uninstall.sh
scale-tests/templates/gensort-application.tmpl
scale-tests/templates/monitoring.tmpl
scale-tests/templates/scale-test-application.tmpl
scale-tests/templates/service-account.tmpl
scale-tests/templates/sort-application.tmpl

Resolves [DCOS-60318: Improve gensort job to avoid high latencies while writing to S3](https://jira.mesosphere.com/browse/DCOS-60318)
Originally started as gensort write time improvement which is achieved via committer configuration property:
```
"spark.hadoop.mapreduce.fileoutputcommitter.algorithm.version": "2"
```
This PR includes refactoring to separate scale tests from the sort benchmark and introduces changes to support ongoing work in https://github.com/mesosphere/spark-build/pull/559 and https://github.com/mesosphere/spark-build/pull/560
These changes are needed to support new scale tests objectives and run the workloads separately.
* by running `gensort` job on a cluster with 40 executors and verifying 1TiB dataset is generated in under 1 hour
* by running all the scripts against …

Scale test scripts updates to support Terasort benchmark, improved S3 write time

---

README.md
images/builder/Dockerfile
kudo-operator/docs/latest/README.md
kudo-operator/docs/latest/history-server.md
kudo-operator/docs/latest/multi-tenancy.md
kudo-operator/docs/latest/versions.md
kudo-operator/operator/operator.yaml
kudo-operator/operator/params.yaml
kudo-operator/operator/templates/spark-history-server-deployment.yaml
kudo-operator/operator/templates/spark-history-server-service.yaml
kudo-operator/operator/templates/spark-operator-deployment.yaml
kudo-operator/operator/templates/spark-operator-rbac.yaml
kudo-operator/operator/templates/spark-operator-serviceaccount.yaml
kudo-operator/operator/templates/spark-rbac.yaml
kudo-operator/operator/templates/spark-serviceaccount.yaml
kudo-operator/operator/templates/webhook-cleanup-job.yaml
kudo-operator/operator/templates/webhook-init-job.yaml
kudo-operator/operator/templates/webhook-service.yaml
tests/basic_test.go
tests/go.mod
tests/tenancy_test.go
tests/utils/common.go

Resolves [DCOS-60787: Update Spark Operator to KUDO 0.8.x](https://jira.mesosphere.com/browse/DCOS-60787).
This PR updates KUDO version and adds necessary changes to templates, `params.yaml`, and `operator.yaml` to address the breaking changes introduced in KUDO 0.8.0.
The changes were needed to address the breaking changes at the earlier stage and simplify later updates to the newer KUDO versions.
* by running `make test` locally
* integration tests from this repo run in [KUDO 0.8.0 CI job](https://teamcity.mesosphere.io/viewType.html?buildTypeId=Frameworks_DataServices_Kudo_Spark_Pr_SparkPrKonvoyKudoV080pre2&branch_Frameworks_DataServices_Kudo_Spark_Pr=pull%2F54&tab=buildTypeStatusDiv)

Operator upgrade to KUDO 0.8.0

---

tests/security_test.go
tests/templates/spark-mock-task-runner-job.yaml
tests/utils/job.go
tests/utils/k8s.go

Resolves [DCOS-60858](https://jira.mesosphere.com/browse/DCOS-60858)
Implements integration tests for environment based secret as well as file based secret. It creates a secret and for the case of file based test, it mounts secret as file and check mounted path in job description. For the case of env based test, it set an environment variable by referencing it to a secret key and check for the environment variable in job description.
To verify File based as well as env based secret working.
Ran `make test` locally.

[DCOS-60858] [Spark Operator] Test mounting secrets

---

kudo-operator/operator/operator.yaml
kudo-operator/operator/templates/spark-operator-deployment.yaml

This PR contains fixes for mutation admission webhook, which used to customize Spark driver and executor pods based on the specification in `SparkApplication` objects. 
After the fix is accepted and verified, it should be applied to https://github.com/kudobuilder/operators/pull/118 as well.
While working on [DCOS-60865: Test pod affinity and tolerations support](https://jira.mesosphere.com/browse/DCOS-60865), it was discovered, that aforementioned features didn't work as expected, even though webhook was enabled by default and service was installed. Operator's description showed the following warning:
```
➜ k describe pod test-instance-5869fb6d47-7tqw5 -n kudo-spark-operator-testing
Warning  FailedMount  66s (x3 over 68s)  kubelet, minikube  MountVolume.SetUp failed for volume …
```

Fix mutating admission webhook

---

tests/templates/spark-linear-regression-history-server-job.yaml
tests/templates/spark-linear-regression-job.yaml

Resolves [DCOS-60993: Master builds fail for tests based on linear regression](https://jira.mesosphere.com/browse/DCOS-60993).
This PR changes the dependency jar URI scheme from remote(`http`) to `local` for `scopt` library which is needed for linear regression application used in tests.
Two of KUDO Spark CI tests started constantly failing for PRs in all branches and on `master`. Failed tests rely on linear regression example application which requires `scopt` option parsing library as a dependency but fails to fetch it.
After verifying that the fetching mechanism works as expected by providing a different location of the same library, it turned out that the issue was in the remote jar file corruption of one form or another. The solution for this specific issue would be switching to …

Switching to 'local' scheme in tests based on Spark examples jar

---

tests/network_test.go
tests/smoke_test.go
tests/templates/spark-linear-regression-history-server-job.yaml
tests/templates/spark-linear-regression-job.yaml
tests/templates/spark-mock-task-runner-job-host-network.yaml
tests/templates/spark-mock-task-runner-job.yaml
tests/templates/spark-pi.yaml
tests/templates/spark-shuffle-job.yaml
tests/utils/job.go

Resolves [DCOS-60860](https://jira.mesosphere.com/browse/DCOS-60860)
- Adds a test for SparkApplication `spec.hostNetwork` parameter behavior according to the [user guide](https://github.com/mesosphere/spark-on-k8s-operator/blob/master/docs/user-guide.md#host-network)
Please note, that this PR temporarily includes changes from #60 as well, to prevent CI builds from failing. Once #60 is merged I'll rebase this PR to make the diff cleaner.
With `make test` in a k8s cluster in AWS.

DCOS-60860 - Test host network support

---

tests/affinity_and_toleration_test.go
tests/templates/spark-mock-task-runner-job.yaml

Resolves [DCOS-60865: Test pod affinity and tolerations support](https://jira.mesosphere.com/browse/DCOS-60865)
This PR introduces tests for pod affinity rules and tolerations.
Note: tests use new utility methods, that were introduced in #61, this PR will be updated after the aforementioned is merged.
To verify that affinity and toleration rules, defined in `SparkApplication` properly propagated to a pod's specification.
Tested by running the tests locally on minikube cluster as well as running tests from this repo in CI

[DCOS-60865] Test pod affinity and tolerations support

---

images/spark/Dockerfile
tests/security_test.go
tests/templates/spark-mock-task-runner-job.yaml

Resolves [DCOS-60866: Test pod security context](https://jira.mesosphere.com/browse/DCOS-60866)
This PR introduces a test for pod security context as well as a few fixes in Spark base image Dockerfile, which allow running Spark jobs as a non-root user.
Due to insufficient permissions, Spark application failed with errors when running as a `nobody` user.
Pod spec:
```
securityContext:
runAsUser: 65534
runAsGroup: 65534
runAsNonRoot: true
```
Exception in Driver's log:
```
Exception in thread "main" java.lang.NoClassDefFoundError: io/fabric8/kubernetes/client/KubernetesClient
```
```bash
bash-4.4# ls -l /opt/spark/jars/ | grep kubernetes
-rw-------    1 root     root        616644 Aug 23 16:48 kubernetes-client-4.4.2.jar
-rw-r--r--    1 root     root       9386214 Oct 18 01:15 …
```

[DCOS-60866] Test pod security context

---

tests/basic_test.go
tests/templates/spark-mock-task-runner-job.yaml

Resolves [DCOS-60862](https://jira.mesosphere.com/browse/DCOS-60862)
Implements integration tests for mounting volumes support. It uses `hostPath` type of volume for this test. Create a file and check for its existence to verify the volume is writable or not.
To verify volume mounting support
Ran `make test` locally.

[DCOS-60862] [Spark Operator] Test mounting volumes support

---

images/spark/Dockerfile
tests/affinity_and_toleration_test.go
tests/basic_test.go
tests/security_test.go
tests/templates/spark-pi-python.yaml

Resolves [DCOS-61247](https://jira.mesosphere.com/browse/DCOS-61247)
This PR adds Python support to the base Spark docker image. Also, a simple test was added to the test suite to verify python-based applications work correctly.
To add Python support as well as required libraries to base Spark docker image.
by running the new test locally
by running integration test suite in the CI
by verifying environment setup inside a container via `docker run`:
```
bash-4.4# python --version
Python 2.7.16
bash-4.4# python3 --version
Python 3.6.9
```
pyspark example:
```
bash-4.4# /opt/spark/bin/pyspark 
>>> import pyspark
>>> sc = pyspark.SparkContext('local[*]')
19/12/06 13:12:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where …
```

[DCOS-61247] Provide Python support

---

images/spark/Dockerfile
tests/basic_test.go
tests/templates/spark-r-als.yaml

Resolves [DCOS-61620](https://jira.mesosphere.com/browse/DCOS-61620)
This PR adds SparkR support to base Spark image as well as an integration test for exercising R API.  
Add the ability to run SparkR applications on Kudo Spark Operator by updating the base Spark image. 
Also, an integration test was added to the test suite. The test submits SparkR application, which makes a prediction based on Alternating Least Squares algorithm. 
By running the test locally on minikube;
By running tests from this repo in CI.

[DCOS-61620] Provide and test SparkR support

---

tests/basic_test.go
tests/utils/job.go
tests/utils/k8s.go

This PR contains a fix for flaky test:
https://teamcity.mesosphere.io/project.html?projectId=Frameworks_DataServices_Kudo_Spark_Pr&testNameId=2269851367190235341&tab=testDetails
One of the tests is flaky due to a slight deviation of Pi calculation, produced by Spark job:
```
19/12/11 13:03:23 INFO DAGScheduler: Job 0 finished: reduce at /opt/spark/examples/src/main/python/pi.py:44, took 3.725619 s
Pi is roughly 3.133980
```
tests from this repo

Fix flaky test

---

Makefile

Resolves [DCOS-61883: Create a TC job for Spark operator release](https://jira.mesosphere.com/browse/DCOS-61883)
Changes:
- added a fix for the case, when `*-dev` images are not present on a build agent;
- code refactoring
To improve release job stability and improve code clarity.
- by executing `make release` locally (without pushing the images);
- by running a release job in TC: https://teamcity.mesosphere.io/viewLog.html?buildId=2488660&buildTypeId=Frameworks_DataServices_Kudo_Spark_Tools_Release&tab=buildResultsDiv
- by verifying image digests:
https://hub.docker.com/layers/mesosphere/spark/operator-test-release/images/sha256-63cc42f1b880bb806949bb08187c628c6e5d8ace4a100e0cc064f8af849b57eb
https://hub.docker.com/layers/mesosphere/spark-dev/ab36f1f3691a8be2050f3acb559c34e3e8e5d66e/image …

[DCOS-61883] Refactor release target

---

tests/basic_test.go

Resolves [DCOS-62592: TestSparkHistoryServerInstallation test is flaky](https://jira.mesosphere.com/browse/DCOS-62592)
- introduce additional filter to prevent multiple pods in results;
- add SHS pod logs output for troubleshooting in case of errors
to eliminate flakes from tests suite
tests from this repo

[DCOS-62592] Fix TestSparkHistoryServerInstallation test

---

tests/resources/volcano/volcano-0.2.yaml
tests/templates/spark-pi.yaml
tests/volcano_test.go

Resolves [DCOS-61939: Integration test and documentation for Volcano integration](https://jira.mesosphere.com/browse/DCOS-61939)
Adds a test for exercising integration with Volcano (https://github.com/volcano-sh/volcano)
To verify `SparkApplication` runs and completes successfully when using Volcano as a batch scheduler.
test from this repo

[DCOS-61939] Add integration test for Volcano scheduler

---

images/operator/Dockerfile
images/spark/Dockerfile
tests/utils/common.go

Resolves [DCOS-62122](https://jira.mesosphere.com/browse/DCOS-62122)
Contains the following changes:
- make Spark dist a part of Spark image build
- switch to using ubuntu:18.04 as a base image
- refactor Dockerfiles for Spark base and Operator images
This approach will offload the burden of maintaining a separate TC job for building the tarballs and uploading them to Mesosphere prod assets bucket while providing a fully transparent view of the image contents to the end-users.
tests from this repo

[DCOS-62122] Make Spark distribution build a part of Spark Docker image

---

tests/ha_test.go

This PR aims to fix flakiness in HA Test suite.
`TestHASuite/TestFailover` test sometimes fails because of a missing leader pod [(example](https://teamcity.mesosphere.io/viewLog.html?buildId=2532422&tab=buildResultsDiv&buildTypeId=Frameworks_DataServices_Kudo_Spark_Pr_SparkPrKonvoyKudoV080pre2))
As it's turned out, at some point during deployment of the operator, the instance of `ReplicaSet` gets recreated (probably, the initial one has failed), causing previously deployed pods to be deleted. The following changes were introduced to stabilize to test flow:
- `kubectl wait` command was added to `SetupSuite` to explicitly check whether the deployment is in the completed state;
-  `getLeaderElectionRecord` method was updated to check the leader pod exists;
- logically reordered tests in the …

Stabilize HA tests suite

---

images/builder/Dockerfile
tests/tenancy_test.go

Switch to the latest Kudo v0.10.0 
This update will make it possible to install monitoring resources automatically with Spark Operator, introduces new plans support, as well as cli improvements and bugfixes.
tests from this repo

Bump Kudo version to 0.10.0

---

Makefile
tests/basic_test.go
tests/go.sum
tests/utils/common.go
tests/utils/job.go

This PR aims to fix SHS test failures caused by S3 folder deletion when parallel builds are running in CI
Currently, an S3 folder, used as a log directory for storing Spark applications, is removed when the test starts and finishes. This approach must not be used in case when multiple builds are running in parallel in CI. When two tests are running concurrently, one could cause another one to fail due to folder clean-up (example [build log](https://teamcity.mesosphere.io/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2525628&_focus=5696))
The proposed solution is to delegate the clean-up process to the S3 lifecycle management feature and remove clean-up from the test code.
Expiration for `kudo-ds-ci-artifacts/kudo-spark-operator/tests/spark-history-server/*` is set …

Fix for S3 folder removal in Spark History test

---

images/builder/Dockerfile
tests/tenancy_test.go

Resolves [D2IQ-63479](https://jira.d2iq.com/browse/D2IQ-63479)
This PR updates KUDO to 0.10.1 and enables multi-tenancy tests which were disabled previously due to cluster-resource related issue in KUDO 0.10.0.
To update KUDO to the latest version and verify the CRD issue is fixed.
tests from this repo.

Upgrade KUDO to 0.10.1 and un-skip related tests

---

tests/resources/volcano/volcano-0.2.yaml
tests/volcano_test.go

Resolves [D2IQ-64032: Pin Volcano scheduler Docker image versions in tests](https://jira.d2iq.com/browse/D2IQ-64032).
This PR updates docker image versions for Volcano deployment in order to be consistent with the release version.
We need to use version-specific tags for Volcano docker images instead of the `latest`, which are not stable and could cause compatibility issues between Volcano components.
tests from this repo.

D2IQ-64032: Pin Volcano scheduler Docker image versions in tests

---

Makefile
scripts/install_operator.sh
tests/basic_test.go
tests/s3_test.go
tests/security_test.go
tests/templates/spark-linear-regression-history-server-job.yaml
tests/templates/spark-s3-readwrite.yaml
tests/utils/aws_s3.go
tests/utils/common.go
tests/utils/k8s.go
tests/utils/spark_operator.go

Resolves [D2IQ-63474: Integration test and docs for S3 access credentials](https://jira.d2iq.com/browse/D2IQ-63474).
This PR adds an integration test for verifying access to S3 from Spark job and Spark History Server using AWS credentials obtained from `Secrets`. Also, it modifies the existing test for Spark History server to adhere to the new method of handling credentials.
- To check AWS credentials are propagated to Spark applications from a Secret
- To verify a new method of mounting Spark config file containing AWS credentials to the Spark History Server as a Secret, which name is passed via `historyServerSparkConfSecret` KUDO parameter.
PR for docs and updated configuration: https://github.com/kudobuilder/operators/pull/214 
Test job can be found here: …

D2IQ-63474: Integration test and docs for S3 access credentials

---

Makefile
README.md
images/spark/Dockerfile
scripts/install_operator.sh
tests/utils/common.go
tests/utils/spark_operator.go

Resolves [D2IQ-64393: Upgrade Spark Operator to v1beta2-1.1.0 with Spark 2.4.5](https://jira.d2iq.com/browse/D2IQ-64393)
To upgrade to the latest stable Apache Spark release and the corresponding Spark Operator release supporting this version.
* integration tests from this repo

Upgrade Spark from 2.4.4 to 2.4.5, upgrade Spark Operator from 1.0.1 to 1.1.0

---

README.md
scripts/install_operator.sh
tests/utils/common.go
tests/utils/spark_operator.go

Resolves [D2IQ-64395: Release KUDO Spark 1.0.0 to KUDO repository](https://jira.d2iq.com/browse/D2IQ-64395).
This PR contains updates related to the new release of Spark Operator.
The operator release PR:  https://github.com/kudobuilder/operators/pull/232
To test the new release
test from this repo
Signed-off-by: Alex Lembiewski <alembiyeuski.c@d2iq.com>

KUDO Spark Operator 2.4.5-1.0.0 release

---

.github/workflows/release.yml
README.md

This PR adds release automation workflow based on GitHub Actions. 
- automate the release process
- to create an operator package automatically and attach it to the release
The workflow was developed and tested in a personal fork, results can be seen here:
- Run: https://github.com/alembiewski/kudo-spark-operator/runs/830062644
- Release example: https://github.com/alembiewski/kudo-spark-operator/releases

Automate release process with Github Actions

---

Makefile
cluster.template.yaml
tests/test-app-scheduling-with-volcano/00-install-volcano.yaml

This PR is related to https://github.com/kudobuilder/operators/pull/297 and bumps the K8s infrastructure versions to use Kubernetes 1.18 in the CI.
To support and verify Spark Operator on Kubernetes 1.18.
* integration tests from this repo
* by manually installing the Operator on Kind with K8s 1.18 and 1.19

Updating Operators CRDs to the latest released version, upgrading Konvoy version to use Kubernetes 1.18

---

.github/workflows/release.yml
Makefile
cluster.template.yaml

This PR upgrades Konvoy from 1.6 RC2 to 1.6 GA and updates release versions in the operator definition and docs.
To synchronize versions in image tags, operator parameters, and documentation.
* the PR build in TeamCity: https://teamcity.mesosphere.io/buildConfiguration/Frameworks_DataServices_Kudo_Spark_Pr_SparkPrKonvoyKudoV0100/3007417?buildTab=overview

Updating Konvoy version to 1.6 GA, synchronize operator and image versions

---

images/spark/conf/metrics.properties
images/spark/conf/prometheus.yaml
tests/test-s3/templates/spark-s3-readwrite.yaml
tests/test-spark-history-server/templates/mock-task-runner.yaml

Resolves [D2IQ-73804: Fix Dashboards and Metrics](https://jira.d2iq.com/browse/D2IQ-73804).
The root case was in the upgrade of the underlying Java metrics library in Spark (Dropwizard metrics) which lead to a mismatch of the new metrics paths with the Prometheus exporter patterns so the metrics were not exported.
Test application:
```
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
name: mock-task-runner
spec:
type: Scala
mode: cluster
image: mesosphere/spark-dev:e0a5c7f882d34cc9693134c48f8b38c60d4d986d
imagePullPolicy: Always
mainClass: MockTaskRunner
mainApplicationFile: "https://kudo-spark.s3-us-west-2.amazonaws.com/spark-scala-tests-3.0.0-20200819.jar"
arguments:
- "1"
- "6000"
sparkConf:
"spark.scheduler.maxRegisteredResourcesWaitingTime": "2400s" …
```

[bugfix] fixing metrics and Prometheus configs to export JVM metrics

---

tests/test-hdfs-kerberos-shs/hdfs-kerberos/datanode-deployment.yaml
tests/test-hdfs-kerberos-shs/hdfs-kerberos/kerberos-deployment.yaml
tests/test-hdfs-kerberos-shs/hdfs-kerberos/namenode-deployment.yaml

This PR explicitly specifies resources for HDFS deployments in test to avoid potential issues with OOMKiller.
* running `test-hdfs-kerberos-shs` on a private cluster
* e2e tests from this repo

[flake] explicitly specify HDFS resources in test to avoid OOM
